name: tilawalock
description: "Discipline begins with recitation."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  speech_to_text: ^6.6.2
  usage_stats: ^1.1.0
  installed_apps: ^1.0.3
  flutter_overlay_window: ^0.4.5
  google_fonts: ^6.3.3
  lottie: ^3.1.2
  animate_do: ^3.3.9
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.3.5
  vibration: ^1.9.0
  percent_indicator: ^4.2.3
  home_widget: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/applogo.png
    - assets/images/
